### PR TITLE
Prevent decorator reuse

### LINKED ISSUE #17: Reusing the same middleware instance in two different decorators, can leads to unexpected behavior
Since `request` is stored on the decorator itself, an instance is tied to a single method chain (the last one it is assigned to) and cannot be used to decorate multiple methods.

For example:
``` ruby
mw = Decorator.new
c = Freno::Client.new(...) do |c|
  c.decorate :first, with: mw
  c.decorate :last, with: mw
end

c.decorated(:first)
c.decorated(:last)

c.first # would actually call `last` because `mw.request` is set to the `last` method wrapper?
```

### PR DESCRIPTION
**Pull request by Oneill38**
Fixes #17 

The current behavior allows the reuse of a decorator instance, which as demonstrated in the linked issue, can caused unexpected behavior. We now check to see if a decorator is already registered, and if it is we throw an error.

Also fixed a deprecation warning in here for switching `mocha/mini_test`, to `mocha/minitest`, along with requiring it after `minitest`.

### CODE REVIEW

**Comment by Oneill38** [comment]
@miguelff think I'm going to need your assistance getting `travis-ci` passing

File: lib/freno/client.rb [hunk 1]
```diff
@@ -178,5 +181,20 @@ def decorated(request)
         outermost
       end
     end
+
+    def validate_and_register_decorators(decorators)
+      decorators.each do |decorator|
+        raise DecorationError if already_registered?(decorator)
+        @registered_decorators << decorator
```
Comment (miguelff) [inline lib/freno/client.rb]:
```suggestion
        registered_decorators << decorator
```

File: lib/freno/client.rb [hunk 2]
```diff
@@ -150,6 +151,8 @@ def decorate(request, with:)
         requests = Array(request)
       end
 
+      validate_and_register_decorators(with)
```
Comment (miguelff) [inline lib/freno/client.rb]: as we are only validating, in here, and not registering the decorators per-se, would you mind renaming this to something like 

```suggestion
      validate!(with)
```

File: lib/freno/client.rb [hunk 3]
```diff
@@ -178,5 +181,20 @@ def decorated(request)
         outermost
       end
     end
+
+    def validate_and_register_decorators(decorators)
+      decorators.each do |decorator|
+        raise DecorationError if already_registered?(decorator)
```
Comment (miguelff) [inline lib/freno/client.rb]: Giving this will be noticeable by the use if they are decorating the client wrong, I believe we should provide a descriptive error message indicating why this is failing.  What do you think?

File: lib/freno/client.rb [hunk 4]
```diff
@@ -5,6 +5,7 @@
 
 module Freno
   class Client
+    class DecorationError < StandardError; end
```
Comment (miguelff) [inline lib/freno/client.rb]: Should this extend `ArgumentError` instead? WDYT about moving it to the `errors.rb` file? Maybe not?

Comment (Oneill38) [reply lib/freno/client.rb]: Switched it to `ArgumentError` 👍 It felt a little weird moving it to `errors.rb` because that's nested a level or two down, and not currently included in this file

**Comment by miguelff** [comment]
I cut a release and pushed [v0.7.0](https://github.com/github/freno-client/tree/v0.7.0) to [rubygems](https://rubygems.org/gems/freno-client/versions/0.7.0) :-)
